config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  resources :time_entries, only: [:new, :create, :edit, :update, :destroy]
  get :statistics, to: "statistics#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_entry.rb
require 'contracts'

class TimeEntry < ApplicationRecord
  include Contracts::Core
  include Contracts::Builtin
    
  belongs_to :user

  validates :start_time, presence: true
  validates :end_time, presence: true, if: ->{ manual_creation? || !end_time_was.nil? }
  validates :description, length: {maximum: 250}
  validate :start_time_is_before_end_time, unless: ->{ end_time.nil? || start_time.nil? }
  validate :start_time_does_not_overlap_with_existing_time_entries, unless: ->{ start_time.nil? }
  validate :end_time_does_not_overlap_with_existing_time_entries, unless: ->{ end_time.nil? }
  validate :does_not_overlap_with_active_time_entry, unless:  ->{ end_time.nil? || start_time.nil? }
  validate :does_not_include_existing_time_entry, unless: ->{ end_time.nil? || start_time.nil? }

  class << self
    Contract None => CustomTypes::ActiveRecordRelationOf[TimeEntry]
    def active
      where('end_time IS NULL')
    end

    Contract Or[Date, CustomTypes::DateString] => CustomTypes::ActiveRecordRelationOf[TimeEntry]
    def recorded_on_date(date)
      where('end_time IS NOT NULL and DATE(start_time) = ?', date)
    end

    Contract HashOf[last: CustomTypes::PosInt] => HashOf[String, String]
    def total_time_by_day(last:)
      result = select('DATE(start_time) as date, SUM(end_time - start_time) as total_time')
        .where("DATE(start_time) > DATE('#{Date.current}') - #{Arel.sql(last.to_s)}")
        .group('DATE(start_time)')
        .order('DATE(start_time)')
        .to_a
        .map{ |hash| [hash['date'], hash['total_time']] }.to_h

      ((Date.current - (last - 1).days)..Date.current).each do |date|
        result[date] = '00:00:00' unless result.key?(date)
      end
      
      result
        .sort
        .to_h
        .transform_keys{ |k| k.strftime('%a, %-d %b') }
    end
  end

  Contract None => CustomTypes::PosInt
  def total_time 
    (end_time - start_time).to_i
  end

  Contract None => true
  def set_manual_creation
    @manual_creation = true
  end

  Contract None => Bool
  def manual_creation?
    @manual_creation ||= false
  end

  private 

  def start_time_is_before_end_time
    if start_time >= end_time
      errors.add(:end_time, :invalid, message: "cannot be before or same as start_time")
    end
  end

  def start_time_does_not_overlap_with_existing_time_entries
    time_does_not_overlap_with_existing_time_entries("start_time", start_time)
  end

  def end_time_does_not_overlap_with_existing_time_entries
    time_does_not_overlap_with_existing_time_entries("end_time", end_time)
  end

  def time_does_not_overlap_with_existing_time_entries(field, value)
    scope = TimeEntry.where(user: user).where("start_time <= :time and end_time >= :time", time: value)
    scope = scope.where.not(id: id) unless new_record?
    if scope.exists?
      errors.add(field, :invalid, message: "cannot overlap with an existing time entries")
    end
  end

  def does_not_include_existing_time_entry 
    scope = TimeEntry
    .where(user: user)
    .where("start_time >= :start_time and end_time <= :end_time", start_time: start_time, end_time: end_time)
    scope = scope.where.not(id: id) unless new_record?
   
    if scope.exists?
      errors.add(:base, :invalid, message: "Time entry cannot include time period of an existing time entry")
    end
  end


  def does_not_overlap_with_active_time_entry
    scope = TimeEntry
    .where(user: user)
    .active
    .where("start_time <= :start_time or start_time <= :end_time", start_time: start_time, end_time: end_time)
    scope = scope.where.not(id: id) unless new_record?

    if scope.exists?
      errors.add(:base, :invalid, message: "Time entry cannot overlap with the start of the ative time entry nor it can be in the future if time tracker is active")
    end
  end
end

app/models/user.rb
require 'contracts'

class User < ApplicationRecord
  include Clearance::User
  include Contracts::Core
  include Contracts::Builtin

  has_many :time_entries, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}

  Contract None => String
  def first_name
    name.split(" ").first
  end

  Contract None => CustomTypes::Initials
  def initials
    words = name.split(" ")
    if words.size > 1
      (words.first[0] + words.second[0]).upcase
    else
      words.first[0, 2].upcase
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login
  
  def show
    @time_entries_recorded_today = current_user.time_entries.recorded_on_date(Date.current).order(:start_time)
    if current_user.time_entries.active.exists?
      @active_time_entry = current_user.time_entries.active.first 
    end
    render :show
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :require_login

  def show
    @time_entries_recorded_on_date = current_user.time_entries.recorded_on_date(preview_date).order(:start_time)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def preview_date
    @preview_date ||= params.key?(:preview_date) ? params[:preview_date] : Date.current
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :require_login
  before_action :prevent_multiple_active_time_entries, only: [:create]
  
  def new
    @time_entry = current_user.time_entries.new
  end

  def create
    @time_entry = current_user.time_entries.new(time_entry_params)
    @time_entry.set_manual_creation if manual_creation?
    
    if @time_entry.save
      respond_to do |format|
        format.js
        format.html { redirect_to root_path }
      end
    else
      respond_to do |format|
        format.js { render :alert }
        format.html { render :new }
      end
    end
  end 

  def edit
    @time_entry = current_user.time_entries.find(params[:id])
  end

  def update
    @time_entry = current_user.time_entries.find(params[:id])
    if @time_entry.update(time_entry_params)
      respond_to do |format|
        format.js
        format.html { redirect_to root_path }
      end
    else
      respond_to do |format|
        format.js { head :bad_request }
        format.html { render :edit }
      end
    end
  end

  def destroy
    @time_entry = current_user.time_entries.find(params[:id])
    if @time_entry.destroy
      respond_to :js
    else
      head :bad_request
    end
  end

  private

  def time_entry_params
    params.require(:time_entry).permit(:description, :start_time, :end_time)
  end

  def prevent_multiple_active_time_entries
    if !manual_creation? && current_user.time_entries.active.exists?
      head :bad_request
    end
  end

  def manual_creation?
    params[:time_entry][:manual] || false
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_back_or root_url
    else
      render template: "users/new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_entry_helper.rb
require 'contracts'

module TimeEntryHelper
  include Contracts::Core
  include Contracts::Builtin

  Contract CustomTypes::PosInt => String
  def pp_total_time(seconds)
    hours = seconds / 3600
    mins = seconds / 60 % 60
    secs = seconds % 60

    "#{hours}h #{mins}m #{secs}s"
  end

  Contract CustomTypes::CollectionOf[TimeEntry] => String
  def pp_collection_total_time(time_entries)
    pp_total_time(collection_total_time(time_entries))
  end

  Contract CustomTypes::CollectionOf[TimeEntry] => CustomTypes::PosInt
  def collection_total_time(time_entries)
    time_entries.reduce(0) { |sum, time_entry| sum + time_entry.total_time }  
  end
end

app/views/commons/_avatar.html.erb
<div class="avatar">
  <%= user.initials %>
</div>

app/views/commons/_errors.html.erb
<div style="margin-top: 20px">
  <% errors.each do |error| %>
    <div class="alert alert-danger"> <%= error %> </div>
  <% end %>
</div>

app/views/home/show.html.erb
<div style="margin: auto; width: 900px;">
  <div id="timer_form_container">
  <%= render partial: "time_entries/start_timer_form", locals: { hidden: @active_time_entry.present? } %>
  <% if @active_time_entry.present? %>
    <%= render partial: "time_entries/stop_timer_form", locals: { time_entry: @active_time_entry } %>
  <% end %>
  </div>

  <div class="d-flex justify-content-end mt-2 font-18">
    <%= link_to "Create manually", new_time_entry_path %>
  </div>

  <div class="font-weight-bold mt-5 font-18">
    Total: <span id="total_time" data-total-time="<%= collection_total_time(@time_entries_recorded_today) %>"> <%= pp_collection_total_time(@time_entries_recorded_today) %></span>
  </div>
  <div id="time_entries_list">
    <%= render partial: "time_entries/list_item", collection: @time_entries_recorded_today, as: :time_entry %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light navbar-expand-lg font-18" style="background-color: #e3f2fd;">
      <a class="navbar-brand ml-2 d-flex align-items-center">Time tracker</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <% if signed_in? %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to 'Home', root_path, class: "font-weight-bold ml-2" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Statistics', statistics_path, class: "font-weight-bold ml-4" %>
            </li>
          </ul>
          <span class="nav-item">
            <%= link_to 'Sign out', sign_out_path, method: :delete, class: "font-weight-bold mr-3" %>
          </span>
          <%= render partial: "commons/avatar", locals: { user: current_user } %>
        <% else %>
          <span class="nav-item ml-auto mr-2">
            <%= link_to 'Sign in', sign_in_path, class: "font-weight-bold" %>
          </span>
        <% end %>
      </div>
    </nav>

    <div style="margin-top: 80px; margin-bottom: 40px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/statistics/show.html.erb
<div style="margin: auto; width: 1000px">
  <h2 class='text-center mb-4'>Weekly data</h2>
  
  <%= column_chart current_user.time_entries.total_time_by_day(last: 7), width: '1000px', suffix: 'h' %>

  <div class="mt-5 d-flex justify-content-center">
    <%= form_with url: statistics_path, method: :get, html: { class: "d-flex", style: "width: 400px"} do |form| %>
  
      <%= form.date_field :preview_date, value: @preview_date, class: "form-control mr-2" %>
  
      <%= form.submit "Show", class: "btn btn-primary btn-md" %>
    <% end %>
  </div>

  <div class="font-weight-bold mt-5 font-18">
    Total: <span id="total_time" data-total-time="<%= collection_total_time(@time_entries_recorded_on_date) %>"> <%= pp_collection_total_time(@time_entries_recorded_on_date) %></span>
  </div>
  
  <div id="time_entries_list">
    <%= render partial: "time_entries/list_item", collection: @time_entries_recorded_on_date, as: :time_entry %>
  </div>
</div>

app/views/statistics/show.js.erb
$("#total_time").html("<%= pp_collection_total_time(@time_entries_recorded_on_date) %>");
$("#time_entries_list").html("<%= j(render partial: "time_entries/list_item", collection: @time_entries_recorded_on_date, as: :time_entry) %>");

app/views/time_entries/_form.html.erb
<div class="form-group">
  <%= form.label :description, class: "font-weight-bold" %>
  <%= form.text_field :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :start_time, class: "font-weight-bold" %>
  <%= form.datetime_field :start_time, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :end_time, class: "font-weight-bold" %>
  <%= form.datetime_field :end_time, class: "form-control" %>
</div>

app/views/time_entries/_list_item.html.erb
<div id="<%= dom_id(time_entry) %>" class="d-flex align-items-center border-top mt-2 pt-2">
  <div class=" flex-grow-1"><%= time_entry.description.blank? ? "No description" : time_entry.description %></div>

  <div class ="d-flex flex-column w-100px">
    <span>start time:</span>
    <span><%= time_entry.start_time.strftime("%H:%M:%S") %></span>
  </div>
  
  <div class="d-flex flex-column w-100px">
    <span>end time:</span>
    <span><%= time_entry.end_time.strftime("%H:%M:%S") %></span>
  </div>
  
  <div class="d-flex flex-column w-100px">
    <span>total time:</span>
    <span><%= pp_total_time(time_entry.total_time) %></span>
  </div>
  
  <div  class="d-flex flex-column text-right"  style="width:70px">
    <%= link_to "Edit", edit_time_entry_path(time_entry) %>
    <%= link_to "Delete", time_entry_path(time_entry), method: :delete, remote: true, data: { confirm: "Are you sure you want to delete this time entry?" } %>
  </div>
</div>

app/views/time_entries/_start_timer_form.html.erb
<%= form_with scope: :time_entry, url: time_entries_path, remote: true, html: { id: :start_timer_form, style: "display: #{hidden ? 'none' : 'flex'}" } do |f| %>
  <%= f.text_field :description, class: "flex-grow-1", placeholder: "What are you working on, #{current_user.first_name}?"  %>
  
  <%= f.hidden_field :start_time %>
  
  <div class="time-counter">00:00:00</div>
  
  <%= f.submit "Start", id: :start_timer_btn, class: "btn btn-primary btn-md w-100px" %>
<% end %>

app/views/time_entries/_stop_timer_form.html.erb
<%= form_for time_entry, remote: true, html: { id: :stop_timer_form, class: "d-flex" } do |f| %>
  <%= f.text_field :description, class: "flex-grow-1", placeholder: "What are you working on, #{current_user.first_name}?" %>
  
  <%= f.hidden_field :end_time %>
  
  <div data-timer="<%= time_entry.start_time.strftime("%Y-%m-%dT%H:%M:%S") %>" class="time-counter"></div>
  
  <%= f.submit "Stop", id: :stop_timer_btn, class: "btn btn-primary btn-md w-100px"%>
<% end %>

app/views/time_entries/alert.js.erb
alert('<%= @time_entry.errors.full_messages.first %>');

app/views/time_entries/create.js.erb
$('#start_timer_form').css('display', 'none');
$('#start_timer_form > #time_entry_description').val("");

$('#timer_form_container').append("<%= j render partial: "time_entries/stop_timer_form", locals: { time_entry: @time_entry } %>");

app/views/time_entries/destroy.js.erb
$('#<%= dom_id(@time_entry) %>').attr('data-marked-for-destruction', true);

$('#total_time').each(function(index, el) {
  const oldTotalTime = Number(el.dataset.totalTime);
  el.dataset.totalTime = `${oldTotalTime - Number('<%= @time_entry.total_time %>')}`;
});

app/views/time_entries/edit.html.erb
<div class="default-form">
  <%= form_with model: @time_entry, local: true do |form| %>
    <%= render partial: "form", object: form %>

    <%= form.submit "Update", class: "btn btn-primary btn-md btn-block" %>
  <% end %>

  <%= render partial: 'commons/errors', object: @time_entry.errors.full_messages %>
</div>

app/views/time_entries/new.html.erb
<div class="default-form">
  <%= form_with model: @time_entry, local: true do |form| %>
    <%= render partial: "form", object: form %>

    <%= form.hidden_field :manual, value: true %>
    
    <%= form.submit "Create", class: "btn btn-primary btn-md btn-block" %>
  <% end %>

  <%= render partial: 'commons/errors', object: @time_entry.errors.full_messages %>
</div>

app/views/time_entries/update.js.erb
$('#start_timer_form').css('display', 'flex');
$('#stop_timer_form').attr('data-marked-for-destruction', true);

$('#time_entries_list').append("<%= j(render partial: "time_entries/list_item", locals: { time_entry: @time_entry }) %>");
$('#total_time').each(function(index, el) {
  const oldTotalTime = Number(el.dataset.totalTime);
  el.dataset.totalTime = `${oldTotalTime + Number('<%= @time_entry.total_time %>')}`;
});

app/views/users/_form.html.erb
<div class="form-group">
  <%= form.label :name, class: "font-weight-bold" %>
  <%= form.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :email, class: 'font-weight-bold' %>
  <%= form.text_field :email, type: 'email', class: "form-control"  %>
</div>

<div class="form-group">
  <%= form.label :password, class: "font-weight-bold" %>
  <%= form.password_field :password, class: "form-control"  %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="default-form">
  <h2 class="mb-4 d-flex justify-content-center"><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="d-flex justify-content-center">
      <%= form.submit class: "btn btn-primary btn-lg btn-block" %>
    </div>
  <% end %>
 
 <div class="other-links text-center mt-2">
       <span> Have an account? </span>
        <%= link_to t(".sign_in"), sign_in_path %>
  </div>

  <%= render partial: 'commons/errors', object: @user.errors.full_messages %>
</div>